version: "3"
services:
    homeassistant:
      container_name: home-assistant
      image: homeassistant/home-assistant
      volumes:
        - /Users/thomasmonaco/HomeAutomation/config:/config
      restart: always
      ports: 
        - 8123:8123
